apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.name }}
  labels:
     microservice: {{ .Values.global.name }}
spec:
   type: ClusterIP
   ports:
   - port: 8888
   selector:
      microservice: {{ .Values.global.name }}
